language: java
deploy:
  provider: releases
  api_key:
    secure: "exricN6q+QIodctLV+8fyZKfPZspRtBpO50qstsPYWreHQo/WPJnO2LbI+y3AHOZRdLrfC2UdFdaK7fXT2RX3I7DbMxMZm1E1rVYXjwU9czQW9NUgvJEQOaVg2k3sBs0y4AxqaEPk34xAy1EWUmx7//H2cCHg3zCaYYcJfjpQsI="
  file: build/libs/gl2gh_im.jar
  skip_cleanup: true
  on:
    tags: true
